language: ruby
rvm:
  - 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: SJryg6Zg5RZTEmH+C29PPB4vVitCY9mlQXDbHOwH8+AYhDSFXrmfqYV3JiqXyuMnjFzhs4kxkmAQ/ynX7a74kN2zUmEqA7eqIoLJIZKGjIzaDYM2Y0Jscd02ZWYFteA0S02yv875zJ/QZAyAnu8E5ggtEMe1D5Qks3EuAIcR6915l5PphYlTC6vJveO0/tmr3+9+/kd/GJ9arqMzJd3Ycvi4GhgSYxwM1AZhoaxEm5KtZOnjmIPqCFI+Xrvf1NGcgkkNA8bFOR8791DKjm2p5rtUc9ZXSg2kiLWwHIcP8fwdF3Y+ctcMf3ZM1jRwRzCk9M0AROqw2dbW6TBwyGp6MzAIivHYaZp43/5HIwaKp9v/ULFNXDjqZeI92E7QLt6WFa5wOtdH/FBA6MMYc+HbS5GuDNROJzcljx5Bu6+NOjSP3jgutIexRZIA5J+gkXO6B7lonEQAltNLyFteMRFpyXji5g6RQ+ygU2uDMul5SXqiDmEKFe7cEaqAY5XOgic4g7EHRJUV05nJipg4rOa32AGnT/MYO5NXr++Hzacw3kpTVPEutJjYuu/Uxyq/Q9Y/b+bHNi0Z17Mdmmo8EEiWkx8y+6gEKevveUf7PiCo+3zoVJuFTDqpjw6QqGOUA1ptSFhq5lCz8/4L5QcFrosIApg2JZ6z3nZQqZheYOalQoE=
