language: ruby
rvm:
- 2.6.5
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: JiV72DNugohgSnaF7l8836GBK2iovuZMrOtUjiHp8AQl+N2DnfOwL+vj/3D7UMCknW4Pl4UwXXbS7XtSQ8K9K324VlTERz2XVukI/uKLEJOYXdezSC5suc1EkRZJCaPl9hz82Wu8HJYgyAd7IEIYT+Q48rZ8FP2hS0uTl/Dkjb0Hau3YI8fykvGMsmoAmc7xojVaPHG2UQH7ks2sp1ld0QkATuQOxG+Xhxf2DZg7R0WzPnBTfpZt4qWvyjN0JEY/PMmGrMLP8iGSY46cVm9wMOSXYW99SXQ9s7iiCI4DGh07gltEnxbH0BsOUfmHYYCaxt6LBYS3QZz5meIpFoKa4xRgIzpl0XjgnhoELIsohQEqgV3/k4MS63sOvhXNodDM/LBd2WAw8wzsATrNX1FWsge+5DkVyaWewHDdy/+7NvgyEdLw/eMewiPCZtdp1QYY9Xau9jvfbR51WkoziA+/gLlbGfyO/PpqSleaiPi0yOiDjlsYU0xPx5NgcFZsqPvJ4x1wm7xyba4+vjsWLXYnRoFTCR5K4WZzDboK1iCJT3boJRl2Xr2hxOOX24866AZO6emYURRsYc5Yg8OIKuLXVXdcJ9HZPPCyTA6t1sXk5OwqtxwxflIXuzydGjDt/mkjCOnpOSkGKw5sSXrKrlQRm5FYPycrlwENx9gC+9nU+Rw=
